directories:
  output: dist
  buildResources: bundle

files:
  - bundle/**/*.js
  - bundle/**/*.css
  - main.html
  - img/**/*

npmRebuild: false

extraFiles:
  - {
      from: "bundle",
      to: "./",
      filter: ["*.node"]
    }
win:
  icon: ./img/icons/win/icon.ico
  target:
    - nsis
    - zip
  publish:
    - github

mac:
  icon: ./img/icons/mac/icon.icns
  category: public.app-category.utility
  target:
    - dmg
    - zip
  publish:
    - github

nsis:
  allowToChangeInstallationDirectory: true
  oneClick: false
  perMachine: true